### ISSUE TITLE
Wrong path

### ISSUE THREAD

**Issue by Madis0** [PojavLauncherTeam/CurseForge-GUI#2]
I installed Fabric Loader and then Fabulously Optimized through this, it created the launcher profile with proper icon and name but it launches an empty Fabric Loader instance 🤔

This is the path it uses:
![image](https://user-images.githubusercontent.com/8611110/232312706-e1134bfb-8080-499b-8fe2-f4597515f561.png)

And this is what it should use:
![image](https://user-images.githubusercontent.com/8611110/232312725-2d24d2e9-c78b-4c34-b3ff-bc449cef2bd9.png)

Essentially the path just needs to be relative instead of specific.

Used this jar for testing: https://discord.com/channels/724163890803638273/724164160761626624/1088814021551083571

**Comment by Madis0** [comment]
There is something still up with the paths

> all the mods are going into "curseforge-cli", while the profile is launching from the "modpack" folder

I personally was not able to reproduce it 100% of times, but occasionally still

**Comment by occhicf** [comment]
New build doesn't appear to have fixed the issue,

After installing a modpack with Curseforge-GUI, this is what the path looks like in Pojav
![Screenshot_20230416-191616_PojavLauncher(Minecraft_ Java Edition for Android)](https://user-images.githubusercontent.com/33247035/232329794-4f46d510-e54c-4621-aa9f-1fb01ecdb0c7.png)


While this is the path required to make it work
![Screenshot_20230416-191709_PojavLauncher(Minecraft_ Java Edition for Android)](https://user-images.githubusercontent.com/33247035/232329799-50456342-18bc-433d-bc9e-85e7d0552625.png)
